version: '3.7'

services:
  # Backend Spring Boot
  backend:
    build:
      context: ./  
      dockerfile: Dockerfile  
    ports:
      - "8080:8080"  
    environment:
      - JDBC_URL=jdbc:postgresql://db:5432/vasara
      - PGUSER=vasara_user
      - PGPASSWORD=vasara_password
      - RABBITMQ_URL=amqps://ksbehmmj:BOKIqQqXiu0GsSlr9rzA-MTrglveM4Bm@duck.lmq.cloudamqp.com/ksbehmmj
      - MAIL=removed
      - MAIL_PASSWORD=removed
      - SECRET=z4kM3fT6Mf6Yk3X1YlI+dmFz1vD8NB4O6ARe3VrjEBg=
    depends_on:
      - db  

  # Frontend (nginx)
  frontend:
    build:
      context: ./VasaraF  
    ports:
      - "8081:80"  

  # PostgreSQL
  db:
    image: postgres:13
    environment:
      - POSTGRES_USER=vasara_user
      - POSTGRES_PASSWORD=vasara_password
      - POSTGRES_DB=vasara
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"  

volumes:
  postgres_data:
