[[builds]]
  path = "vasara/vasaraF"
  build = "npm run build"
  start = "serve -s dist/spa -l $PORT"
  env = { "CI" = "true" }

[[builds]]
  path = "vasara/src"
  build = "mvn clean install"
  start = "java -jar target/vasara.jar"
  env = { "CI" = "true" }
