[[builds]]
  # Definiujemy frontend
  path = "vasara/vasaraF"
  build = "npm run build"
  start = "serve -s dist/spa -l $PORT"  # Railway ustawi zmienną PORT na odpowiedni port
  env = { "CI" = "true" }

[[builds]]
  # Definiujemy backend
  path = "vasara/src"
  build = "mvn clean install"  # Komenda do budowania backendu w Mavenie
  start = "java -jar target/vasara.jar"  # Uruchamianie backendu
  env = { "CI" = "true" }
